### ISSUE TITLE
Failed to read env  GITHUBAPP_KEY variable 

### ISSUE THREAD

**Issue by shreekarSS** [thoth-station/ttm-as-a-service#26]
## Bug description

Failed to read GITHUBAPP_KEY private key which is set in .env file

ValueError: ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [_OpenSSLErrorWithText(code=75497574, lib=9, reason=102, reason_text=b'error:04800066:PEM routines::bad end line')])

### Steps to Reproduce
1. Set up ttm as service github app to the repo which needs prediction 
2. Open pull request with the desired changes

### Actual behavior
Error from github app Recent Deliveries:

<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

Error from Webhook server:

ValueError: ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [_OpenSSLErrorWithText(code=75497574, lib=9, reason=102, reason_text=b'error:04800066:PEM routines::bad end line')])
127.0.0.1 - - [08/Sep/2022 17:04:31] "POST / HTTP/1.1" 500 -

### Expected behavior
To parse the ENV variables successfully and run webhook server for pull request event and comment on the PR with prediction

**Comment by shreekarSS** [comment]
Thinking to read .pem file instead of pasting it's content in env variable. WDYT? @KPostOffice @Gkrumbach07

**Comment by Gkrumbach07** [comment]
reading from a `.pem` file is probably a better method for local development. In production, in openshift at least, it seems easier to inject an environment variable instead of placing a file in a volume in a container which we then pass a path too.
